### ISSUE TITLE
Issue with Building septentrio_gnss_driver in ROS2: Missing Branch

### ISSUE THREAD

**Issue by f-mp** [septentrio-gnss/septentrio_gnss_driver#130]
I am currently trying to build the septentrio_gnss_driver in ROS2. However, the command git checkout ros2 does not work. When I check with git branch -a, only origin/master is available and the ros2 branch cannot be found. Can you help me with this issue?

**Comment by thomasemter** [comment]
Since the latest update, the `ros2`-branch is not needed anymore. The driver can be compiled for both ROS 1 and ROS 2 from the `master` branch.

**Comment by f-mp** [comment]
The branch is not needed.

Thank you.
