### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by js-fwr** [septentrio-gnss/septentrio_gnss_driver#137]
Hi, i tried to build the latest release of your septentrio driver, but unfortunalty this is leading to a few problems: 
it seems to mess up my colcon as well as it didnt build. 

System specs: 

- OS: Ubuntu 22.04
- Ros version: ROS2 Humble
 
Steps: 

1. Copied packages into ros2 src folder of workspace
2. run `colcon build --packages-select-septentrio_gnss_driver_ros2`

Result: 

> colcon build --packages-select septentrio_gnss_driver_ros2
/home/johannes/.local/lib/python3.10/site-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
  warnings.warn(
/home/johannes/.local/lib/python3.10/site-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'install-scripts' will not be supported in future versions. Please use the underscore name 'install_scripts' instead
  warnings.warn(
/home/johannes/.local/lib/python3.10/site-packages/setuptools_scm/_integration/setuptools.py:31: RuntimeWarning: 
ERROR: setuptools==59.6.0 is used in combination with setuptools_scm>=8.x
>
>Your build configuration is incomplete and previously worked by accident!
setuptools_scm requires setuptools>=61
>
>Suggested workaround if applicable:
> - migrating from the deprecated setup_requires mechanism to pep517/518
   and using a pyproject.toml to declare build dependencies
   which are reliably pre-installed before running the build tools
>
>  warnings.warn(
[0.677s] WARNING:colcon.colcon_core.package_selection:ignoring unknown package 'septentrio_gnss_driver_ros2' in --packages-select
[0.705s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/johannes/ros2_ws/install/septentrio_gnss_driver' in the environment variable AMENT_PREFIX_PATH doesn't exist
[0.705s] WARNING:colcon.colcon_ros.prefix_path.catkin:The path '/home/johannes/ros2_ws/install/septentrio_gnss_driver' in the environment variable CMAKE_PREFIX_PATH doesn't exist
>                     
>Summary: 0 packages finished [0.66s]

**Comment by thomasemter** [comment]
Hi @js-fwr,
the package name is `septentrio_gnss_driver`, there is no `_ros2` at the end.
