### ISSUE TITLE
[BUG] SBF log file playback feature failure

### ISSUE THREAD

**Issue by nocoinman** [septentrio-gnss/septentrio_gnss_driver#34]
### Description of bug

Driver fails to detect files when path to file is provided with slashes ('/').

### Environment

Driver was compiled and launched in a Debian-stretch based docker container with ROS Melodic.

### To Reproduce

Specify device in the parameter file as shown

```yaml
device: file_name:/dir1/dir2/file.sbf
```

### Expected behavior

Driver not able to recognise device.

### Suspected cause of bug

Regex used to detect device specified seems to be incorrect.

### Files
Suspected source of bug - https://github.com/septentrio-gnss/septentrio_gnss_driver/blob/dcc3adfbe07da50869a0a8dffdf0b582b6e664ab/src/septentrio_gnss_driver/node/rosaic_node.cpp#L478

**Comment by tibordome** [comment]
Thank you for reporting the bug, and for fixing it!
