### ISSUE TITLE
Heading offset

### ISSUE THREAD

**Issue by tiesus** [septentrio-gnss/septentrio_gnss_driver#79]
Hello, 

I have a question regarding the `antenna_offset:heading` parameter: If i use this parameter with `ros_axis_orientation` is the offset applied to the values complying with the ros_axis_orientation(enu) or to the default NED frame?

**Comment by thomasemter** [comment]
Hello,

I assume you mean `att_offset:heading`. This is defined in body coordinates, which is front-left-up for `ros_axis_orientation` and front-right-down otherwise.

**Comment by tiesus** [comment]
Exactly, i  meant `att_offset:heading`. Thanks for your answer and the clarification:)
